In [1]:
import os
import sys
from datetime import datetime
from IPython.display import HTML

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

WIDTH = 1100
pd.options.display.float_format = 'R$ {:,.2f}'.format

caminho_commons = os.path.join('../..', '..', 'ajna_docs', 'commons')
caminho_virasana = os.path.join('../..', '..', 'ajna_docs', 'virasana')
sys.path.append(caminho_commons)
sys.path.append('../..')
sys.path.append(caminho_virasana)

from ajna_commons.flask.conf import DATABASE, MONGODB_URI

from bhadrasana.models import engine


def AnoMes(row):
    return str(row.Ano) + str(row['Mês']).zfill(2)

2026-03-27 15:06 ajna         INFO     Configuração de log efetuada

2026-03-27 15:06:46,796 ajna         INFO     Configuração de log efetuada

In [3]:
SQL_PENDENTE = \
    '''SELECT r.nome as Recinto, ficha.id as 'Ficha', rvf.id as 'RVF', rvf.datahora 'Data de Abertura',
     ficha.numeroCEmercante, rvf.numerolote as Contêiner
     FROM ovr_ovrs ficha
     INNER JOIN ovr_verificacoesfisicas rvf ON  rvf.ovr_id = ficha.id
     inner join ovr_flags_ovr flags on flags.rvf_id = ficha.id
     INNER JOIN ovr_recintos r ON r.id = ficha.recinto_id
     where ficha.setor_id = 2 AND ficha.fase in (2, 3)
     ORDER BY r.nome, rvf.datahora'''

df_pendente = pd.read_sql(SQL_PENDENTE, engine)

In [4]:
df_pendente

,Recinto,Ficha,RVF,Data de Abertura,numeroCEmercante,Contêiner
0,ALFANDEGA,10891,10481,2025-03-28 10:23:45,None,None
1,BANDEIRANTES DEICMAR - CLIA ALEMOA,2268,1619,2021-06-29 11:51:00,152105130137807,MRSU4106682
2,BANDEIRANTES DEICMAR - CLIA ALEMOA,2225,1714,2021-07-19 10:10:00,152105110560240,CLHU8513070
3,BANDEIRANTES DEICMAR - CLIA ALEMOA,2398,1735,2021-07-27 14:55:00,152105130139770,TGBU6766220
4,BANDEIRANTES DEICMAR - CLIA ALEMOA,2517,1842,2021-08-20 16:25:00,152105187235816,MRKU3234520
...,...,...,...,...,...,...
198,SANTOS BRASIL PARTICIPACOES S/A - OPERADOR,14024,12559,2026-03-18 09:47:00,152605068233653,MRSU9173831
199,SANTOS BRASIL PARTICIPACOES S/A - OPERADOR,14036,12598,2026-03-23 10:00:00,152605068242563,MRSU9287120
200,TERMARES IPA,5657,4750,2023-03-03 12:54:00,152305040731562,
201,TRANSBRASA IPA,2474,1797,2021-08-10 11:18:00,152105182096087,TEMU4683554
202,TRANSBRASA IPA,2370,1846,2021-08-25 18:28:00,152105130137300,MSKU9256982

In [5]:
today_ = datetime.today()
df_pendente.apply(lambda x: (today_ - x['Data de Abertura']).days, axis=1)

0       364
1      1732
2      1712
3      1704
4      1679
       ...
198       9
199       4
200    1120
201    1690
202    1674
Length: 203, dtype: int64

In [7]:
lista_ovr = ', '.join([str(i) for i in df_pendente.Ficha.values])

# Colocar os códigos embaixo

In [11]:
SQL_PENDENTE = \
    '''SELECT r.nome as Recinto, ficha.id as 'Ficha', rvf.id as 'RVF', rvf.datahora 'Data de Abertura',
     ficha.numeroCEmercante, rvf.numerolote as Contêiner
     FROM ovr_ovrs ficha
     INNER JOIN ovr_verificacoesfisicas rvf ON  rvf.ovr_id = ficha.id
     inner join ovr_flags_ovr flags on flags.rvf_id = ficha.id
     INNER JOIN ovr_recintos r ON r.id = ficha.recinto_id
     where ficha.setor_id = 2 AND ficha.fase in (2, 3)
     ORDER BY r.nome, rvf.datahora'''

df_pendente = pd.read_sql(SQL_PENDENTE, engine)
today_ = datetime.today()
def calcula_dias(x):
    try:
        return int((today_ - x['Data de Abertura']).days)
    except:
        return 0
            

df_pendente['Dias sem conclusão'] = \
    df_pendente.apply(calcula_dias, axis=1)
lista_ovr = ', '.join([str(i) for i in df_pendente.Ficha.values])

SQL_EVENTOS = \
    '''SELECT ovr_id as Ficha, tipoevento_id, t.nome, e.create_date, motivo FROM ovr_eventos e
    inner join ovr_tiposevento t on e.tipoevento_id = t.id  where ovr_id in (%s)
    ORDER BY ovr_id;'''

df_eventos = pd.read_sql(SQL_EVENTOS % lista_ovr, engine)


# Tipos de Evento : 36 Em análise da Fiscalização
#                    7 Aguardando quantificação do Recinto
#                   21 Termo de Guarda informado
#                   8 Recebimento de quantificação do Recinto
df_pendente = df_pendente.drop_duplicates(subset=['Ficha'])
df_pendente = df_pendente.set_index('Ficha')
df_pendente = df_pendente.join(
    df_eventos[df_eventos.tipoevento_id == 36].drop_duplicates(
        ('Ficha', 'tipoevento_id'))[['Ficha', 'motivo']].set_index('Ficha')
)

In [12]:
df_pendente = df_pendente.rename(columns={'motivo': 'Parecer'}).fillna('--')

In [13]:
df_pendente.replace({'SANTOS/BRASIL SA OPERADOR PORTUARIO': 'SANTOS BRASIL PARTICIPACOES LTDA' }, inplace=True)

In [14]:
tipos_eventos = {36: 'Análise',
                 7: 'Saneamento solicitado',
                 8: 'Saneamento recebido',
                 21: 'TG recebido'}
for tipoevento_id, descricao in tipos_eventos.items():
    df_pendente = df_pendente.join(
        df_eventos[df_eventos.tipoevento_id == tipoevento_id].drop_duplicates(
            ('Ficha', 'tipoevento_id'))[['Ficha', 'create_date']].set_index('Ficha')
    )
    df_pendente = df_pendente.rename(columns={'create_date': descricao}).fillna('Sem evento')

In [15]:
recintos = df_pendente['Recinto'].unique()
df_pendente['Recinto'].value_counts()

Recinto
SANTOS BRASIL PARTICIPACOES S/A - OPERADOR            32
EMBRAPORT - EMPRESA BRASILEIRA DE TERMINAIS PORTUA    28
EUDMARCO - PORTO SECO                                 21
BANDEIRANTES DEICMAR - IPA OUTEIRINHOS                13
OP - SANTOS/BRASIL SA OPERADOR PORTUARIO              11
BANDEIRANTES DEICMAR - CLIA ALEMOA                     6
Brasil Terminal Portuario                              5
SANTOS BRASIL LOGISTICA S/A - CLIA SANTOS              2
TRANSBRASA IPA                                         2
ALFANDEGA                                              1
DEICMAR SABOO - IPA                                    1
ECOPORTO SANTOS - TERMINAL 1                           1
ECOPORTO SANTOS - TERMINAL 3                           1
OP. - EMBRAPORT OPERADOR                               1
TERMARES IPA                                           1
Name: count, dtype: int64

In [17]:
def duracao(x):
    try:
        return (x['Saneamento recebido'] - x['Data de Abertura']).days
    
    except:
        try:
            return (x['TG recebido'] - x['Data de Abertura']).days
        except:
            return 0
df_pendente['Duração'] = df_pendente.apply(duracao, axis=1)

In [18]:
len(df_pendente[df_pendente['Recinto'] == 'BANDEIRANTES DEICMAR - CLIA ALEMOA'])

6

In [ ]:
def mostra_recinto(recinto, filtrar_concluidos=False):
    print(recinto, len(df_pendente_outlet[df_pendente_outlet['Recinto'] == recinto]))
    df_pendentes = df_pendente.reset_index()
    df_pendentes = df_pendentes[['Ficha', 'Recinto', 'Data de Abertura', 'numeroCEmercante', 'Dias sem conclusão',
                                 'Parecer', 'Contêiner', 'Saneamento recebido', 'TG recebido', 'fase', 'Duração']]
    df_pendentes.sort_values(['Ficha'], inplace=True)
    if filtrar_concluidos:
        df_pendentes=df_pendentes[df_pendentes['fase'] != 3]
        df_pendentes=df_pendentes[df_pendentes['fase'] != 4]
        df_pendentes=df_pendentes[df_pendentes['TG recebido'] == 'Sem evento']
    return df_pendentes[df_pendentes['Recinto'] == recinto]

In [ ]:
mostra_recinto(recintos[0])

In [ ]:
mostra_recinto(recintos[0], True).drop(columns=['Parecer', 'fase']).style.hide_index()

In [ ]:
mostra_recinto(recintos[1])

In [ ]:
mostra_recinto(recintos[1], True).drop(columns=['Parecer', 'fase']).style.hide_index()

In [ ]:
mostra_recinto(recintos[7], True).drop(columns=['Parecer', 'fase']).style.hide_index()

In [ ]:
paradigma = mostra_recinto(recintos[4])
paradigma

In [ ]:
paradigma[paradigma['Duração']==0]

In [ ]:
paradigma_conclusos = paradigma[paradigma['Duração']!=0]
print('Duração média: ', paradigma_conclusos['Duração'].mean())
print('Quantidade concluídos:', len(paradigma_conclusos))
print('Data primeiro e último:', min(paradigma_conclusos['Data de Abertura']), max(paradigma_conclusos['Data de Abertura']))

In [20]:
resumo_recintos = {}
for recinto in recintos:
    df_recinto = df_pendente[(df_pendente.Recinto == recinto)]
    concluidos = 0
    pendentes = 0
    tempoc = 0
    tempop = 0
    for row in df_recinto.iterrows():
        if row[1]['Duração'] == 0:  # Não concluído / pendente
            p = row[1]['Dias sem conclusão']
            tempop += p
            pendentes += 1
        else:  # Concluído
            c = row[1]['Duração']
            tempoc += c
            concluidos += 1
    resumo_recintos[recinto] = {
        'concluídos': concluidos,
        'duração média': 0 if concluidos == 0 else int(tempoc / concluidos),
        'pendentes': pendentes,
        'dias sem conclusão média': 0 if pendentes == 0 else int(tempop / pendentes)
    }
df_resumo = pd.DataFrame.from_dict(resumo_recintos, orient='index')
df_resumo['% Concluído'] = (df_resumo['concluídos'] / (df_resumo['concluídos'] + df_resumo['pendentes']))*100

In [21]:
pd.options.display.float_format = '{:,.2f}%'.format
df_resumo.dropna()

,concluídos,duração média,pendentes,dias sem conclusão média,% Concluído
ALFANDEGA,0,0,1,364,0.00%
BANDEIRANTES DEICMAR - CLIA ALEMOA,6,325,0,0,100.00%
BANDEIRANTES DEICMAR - IPA OUTEIRINHOS,12,428,1,1710,92.31%
Brasil Terminal Portuario,4,62,1,1051,80.00%
DEICMAR SABOO - IPA,1,32,0,0,100.00%
ECOPORTO SANTOS - TERMINAL 1,1,40,0,0,100.00%
ECOPORTO SANTOS - TERMINAL 3,1,131,0,0,100.00%
EMBRAPORT - EMPRESA BRASILEIRA DE TERMINAIS PORTUA,15,88,13,470,53.57%
EUDMARCO - PORTO SECO,20,162,1,1718,95.24%
OP - SANTOS/BRASIL SA OPERADOR PORTUARIO,11,89,0,0,100.00%
OP. - EMBRAPORT OPERADOR,1,315,0,0,100.00%
SANTOS BRASIL LOGISTICA S/A - CLIA SANTOS,2,141,0,0,100.00%
SANTOS BRASIL PARTICIPACOES S/A - OPERADOR,30,174,2,6,93.75%
TERMARES IPA,1,77,0,0,100.00%
TRANSBRASA IPA,2,152,0,0,100.00%